config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#home'

  resources :products do
    resources :reviews, :except => [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :cost, :origin, :presence => true

  has_many :reviews

  scope :most_reviewed, -> {
    select("products.id, products.name, products.cost, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group('products.id')
    .order('reviews_count DESC')
    .limit(1)
  }

  scope :recently_added, -> { order(created_at: :desc).limit(3) }

  scope :domestic, -> { where('origin = ?', 'United States') }

end

app/models/review.rb
class Review < ApplicationRecord
  validates :author, :content, :rating, :presence => true
  validates :rating, :numericality => { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :content, :length => { minimum: 50, too_short: 'must be at least 50 characters', maximum: 250, too_long: 'must be less than or equal to 250 characters' }

  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: 'Product successfully added!'
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product), notice: 'Product successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.reviews.each do |review|
      review.destroy
    end
    @product.destroy
    redirect_to products_path, notice: 'Product successfully deleted!'
  end

private

  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_product

  def new
    @review = Review.new
  end

  def create
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product), notice: 'Successfully added review!'
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@product), notice: 'Successfully edited review!'
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product), notice: 'Successfully deleted review!'
  end

private

  def review_params
    params.require(:review).permit(:author, :content, :rating)
  end

  def find_product
    @product = Product.find(params[:product_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id='errors' class='container card'>
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpecialtyFoods</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="<%= yield(:background) %>">

      <div class="ui menu">
        <div class="header item">
          Specialty Foods Market
        </div>
        <div class="right menu">
          <a class="item" href='/'>
            Home
          </a>
          <a class="item" href='/products'>
            Products
          </a>
        </div>
      </div>

      <div id='flash' class='ui container'>
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>

      <div class='ui container'>
        <%= yield %>
      </div>

    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render 'layouts/errors', :object => @product %>

<%= form_for @product, html: {class: 'ui form'} do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class='form-group'>
    <%= f.label :cost %>
    <br>
    <%= f.text_field :cost %>
  </div>
  <div class='form-group'>
    <%= f.label :origin %>
    <br>
    <%= f.text_field :origin %>
  </div>
  <%= f.submit :class => 'ui positive basic button'%>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product: <%= @product.name %></h1>

<%= render 'form' %>

app/views/products/home.html.erb
<% content_for(:background, "home_background") %>

<h1 id="home_header">Welcome to Specialty Foods Market</h1>

app/views/products/index.html.erb
<% content_for(:background, "products_background") %>

<h1>All Products</h1>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>

<%= link_to 'Add New Product', new_product_path, :class => 'btn btn-outline-success' %>

<hr>

<h1>Featured Products</h1>

<h4>Most Reviewed:</h4>
<ul>
  <li><%= link_to @products.most_reviewed[0].name, product_path(@products.most_reviewed[0]) %></li>
</ul>

<h4>Recently Added:</h4>
  <ul>
    <% @products.recently_added.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>

  <h4>Domestic Products:</h4>
    <ul>
      <% @products.domestic.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>

app/views/products/new.html.erb
<h1>Add a New Product to the Inventory</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<h3>Cost: $<%= @product.cost %></h3>
<h3>Country of Origin: <%= @product.origin %></h3>

<%= link_to 'Update Product', edit_product_path(@product), :class => 'btn btn-outline-primary' %>
<%= link_to 'Delete Product', product_path(@product), :method => 'delete', :data => { :confirm => 'Are you sure?'}, :class => 'btn btn-outline-danger' %>

<hr>

<h3>Reviews</h3>

<%= link_to 'Submit New Review', new_product_review_path(@product), :class => 'btn btn-outline-success' %>

<br><br>

<ul>
  <% @reviews.each do |review| %>
    <li>(<%= review.rating %>/5) <%= review.content %></li>
      <ul>
        <li><%= review.author %></li>
        <li>
          <%= link_to 'Edit', edit_product_review_path(@product, review), :class => 'btn btn-outline-primary btn-sm' %>
          <%= link_to 'Delete', product_review_path(@product, review), :method => 'delete', :data => { :confirm => 'Are you sure?'}, :class => 'btn btn-outline-danger btn-sm' %>
        </li>
      </ul>
  <% end %>
</ul>

app/views/reviews/_form.html.erb
<%= render 'layouts/errors', :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <div class='form-group'>
    <%= f.label :author %>
    <br>
    <%= f.text_field :author %>
  </div>
  <div class='form-group'>
    <%= f.label :content %>
    <br>
    <%= f.text_field :content %>
  </div>
  <div class='form-group'>
    <%= f.label :rating %>
    <br>
    <%= f.number_field :rating, in: 1..5, step: 1 %>
  </div>
  <%= f.submit :class => 'btn btn-outline-info'%>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>Add New Review for <%= @product.name %></h1>

<%= render 'form' %>